### ISSUE TITLE
-r option not working properly

### ISSUE THREAD

**Issue by guillermo-carrasco** [SciLifeLab/TACA#53]
```
(master)hiseq.bioinfo@seq-nas-3:/srv/illumina/hiseq_data/nosync$ taca storage archive-to-swestore -r 150113_D00456_0058_AC6KUBANXX.tar.bz2
Traceback (most recent call last):
  File "/home/hiseq.bioinfo/.anaconda/envs/master/bin/taca", line 5, in <module>
    pkg_resources.run_script('taca==1.0', 'taca')
  File "/home/hiseq.bioinfo/.anaconda/envs/master/lib/python2.7/site-packages/setuptools-3.6-py2.7.egg/pkg_resources.py", line 534, in run_script
  File "/home/hiseq.bioinfo/.anaconda/envs/master/lib/python2.7/site-packages/setuptools-3.6-py2.7.egg/pkg_resources.py", line 1434, in run_script
  File "/home/hiseq.bioinfo/.anaconda/envs/master/lib/python2.7/site-packages/taca-1.0-py2.7.egg/EGG-INFO/scripts/taca", line 38, in <module>
    app.run()
  File "/home/hiseq.bioinfo/.anaconda/envs/master/lib/python2.7/site-packages/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
  File "/home/hiseq.bioinfo/.anaconda/envs/master/lib/python2.7/site-packages/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/home/hiseq.bioinfo/.anaconda/envs/master/lib/python2.7/site-packages/cement/core/controller.py", line 461, in _dispatch
    return func()
  File "/home/hiseq.bioinfo/.anaconda/envs/master/lib/python2.7/site-packages/taca-1.0-py2.7.egg/taca/controllers/storage.py", line 56, in archive_to_swestore
    self._archive_run(self.pargs.run)
AttributeError: 'StorageController' object has no attribute 'pargs'
```

**Comment by guillermo-carrasco** [comment]
Ok, fix [here](https://github.com/guillermo-carrasco/TACA/commit/96f8f89bdf1f3e4b836100f955904c137d258ea4), testing it...

- [ ] Test with relative run path
- [ ] Test with absolute run path
